FROM cloudreactor-python-ecs-quickstart

COPY ./dev-requirements.in /tmp/

WORKDIR /tmp

RUN /home/appuser/.local/bin/pip-compile --allow-unsafe --generate-hashes \
  dev-requirements.in --output-file dev-requirements.txt

RUN pip install -r requirements.txt -r dev-requirements.txt

COPY ./mypy.ini .

WORKDIR /home/appuser

ENTRYPOINT ["pytest"]
