FROM cloudreactor-ecs-quickstart

USER root
WORKDIR /usr/src/app

COPY ./dev-requirements.txt .

RUN pip install --no-cache-dir -r dev-requirements.txt

USER appuser
WORKDIR /home/appuser

CMD ["pytest"]

