FROM cloudreactor-ecs-quickstart

USER root
WORKDIR /usr/src/app

COPY ./dev-requirements.in .

RUN pip-compile --allow-unsafe --generate-hashes \
  dev-requirements.in --output-file dev-requirements.txt

RUN pip install --no-input --no-cache-dir -r requirements.txt -r dev-requirements.txt

USER appuser
WORKDIR /home/appuser

COPY ./mypy.ini .

ENTRYPOINT ["pytest"]
