# Do not edit this file directly, it is generated from deploy/Dockerfile.j2
FROM python:3.8.2

LABEL maintainer="jeff@cloudreactor.io"

EXPOSE 7070

WORKDIR /usr/src/app

RUN pip install --upgrade pip==20.0.2

COPY ./requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# Run as non-root user for better security
RUN useradd --create-home appuser
WORKDIR /home/appuser

COPY deploy/files/proc_wrapper_1.2.2.py proc_wrapper.py

# copy deployment environment settings
COPY build/dev/.env .env

CMD $TASK_COMMAND
