FROM python:3.8.2-alpine

LABEL maintainer="jeff@cloudreactor.io"

EXPOSE 7070

WORKDIR /usr/src/app

RUN pip install --upgrade pip

COPY ./requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

COPY deploy/files/proc_wrapper_1.2.2.py proc_wrapper.py

# copy secrets
COPY build/{{ env }}/.env .env

COPY src/*.py ./

CMD python proc_wrapper.py $TASK_COMMAND
