name: Tests
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
        pip install pylint-exit

    - name: Test with pytest
      run: "pytest"
      env:
        PYTHONPATH: src
    - name: Syntax check with pylint
      run: "pylint --rcfile=src/.pylintrc src || pylint-exit --error-fail $?"
      env:
        PYTHONPATH: src
    - name: Type check with mypy
      run: "mypy src"
      env:
        PYTHONPATH: src
    - name: Print final message
      run: "echo Complete"
